/* hmm site - THREE market panels (Australia, New Zealand, Japan). One panel per market.

   2026-09-14. The panels used to carry six axes scored 0 to 10, and their own caption
   declared four of the six "assessed from market structure". An assessment has no file
   behind it, and the rule on this site is that a figure reads from the estate through a
   script or a guarded snapshot, or the sentence stands without it. So the assessed axes
   went and what replaced them is owned, bar by bar:

     THE CHART GEOMETRY   the specialisation index, three spokes for Power, Eat and Heal,
                          the vertex radius being the index itself. The rings sit on the
                          index's own thresholds (1.00 where market size predicts, 1.15
                          where specialisation begins), so changing the datum changes the
                          drawing's shape, which is the constructed-form rule.
     THE MEASURED STRIP   data/market_strength.js, generated by scripts/market-strength.mjs
                          from two owners: the instrument counts from data/reg_instruments.js
                          on the same predicate count_reg_dates.py applies in the estate,
                          and the listing share copied verbatim out of canon.
     THE PROSE            each market's exported instrument, from the memorandum's own
                          market derivation, carrying the fact-check corrections of
                          2026-09.

   The three measured rows are comparable ACROSS markets, because they are counts and a
   share on one denominator. The old scores were not, which is why the old caption had to
   tell a reader to read down a panel and never across. A drawing that needs that
   instruction is a drawing carrying the wrong quantity.

   Three necessity fills per panel (Power, Eat, Heal). Vanilla SVG (createElementNS), no
   libraries. Renders into an existing #radars container on load; no-ops if it is absent.
   Dark by default (bg #141414) to match the live site; light via prefers-color-scheme
   and [data-theme="light"]. Honours prefers-reduced-motion (disables the dot pulse).
   Tokens are read through __T from theme.js and re-read on __onTheme. The stylesheet
   lives in index.css (the #radars rules). The dot flock is the core identity motion and
   is unchanged: it samples the polygon the index draws rather than the one the scores
   drew. */
(function () {
  var SVGNS = "http://www.w3.org/2000/svg";

  /* Three spokes, one per necessity, in the order the systems are stated everywhere else. */
  var AXES = ["POWER", "EAT", "HEAL"];

  // Necessity palette (exact hues, matched to the rest of the site). Read
  // from the tokens at every render: hues() is called for the first paint and
  // again on a data-theme flip, and HUES is refreshed in place so every
  // reader of it (the swatches, the series paths, the canvas dots) sees the
  // new value without being rebuilt.
  function hues() { return { Power: __T("--hmm-nec-power-dark", "#FF9732"), Eat: __T("--hmm-nec-eat-dark", "#508B5C"), Heal: __T("--hmm-nec-heal-dark", "#9E69BE") }; }
  var HUES = hues();
  var SERIES = ["Power", "Eat", "Heal"];
  /* AXES are set in caps for the drawing; SPEC and HUES key on the house spelling. */
  function CAP(a) { return a.charAt(0) + a.slice(1).toLowerCase(); }

  // dots render on <canvas> using the DWG-NEC machine-flock physics; PANELS collects them per panel.
  var PANELS = [];
  /* How many panels the pointer is inside. lockHeights() must not measure a panel while it is
     expanded, and reading `:hover` through querySelector would be a selector that can never
     match in a headless probe, which check:deadjs correctly rejects. A counter also behaves on
     touch, where the hover state does not exist at all. */
  var HOVERING = 0;
  function hexA(h, a) { var n = parseInt(h.slice(1), 16); return "rgba(" + ((n >> 16) & 255) + "," + ((n >> 8) & 255) + "," + (n & 255) + "," + a + ")"; }

  /* Name, code and one descriptor. No scores: the geometry reads the specialisation index
     and the strip reads data/market_strength.js. `code` is the key into both owners. */
  var MARKETS = [
    { name: "AUSTRALIA",   code: "AU", sub: "resource and materials market" },
    { name: "NEW ZEALAND", code: "NZ", sub: "standard-setting market" },
    { name: "JAPAN",       code: "JP", sub: "hardware market under demand stress" }
  ];

  // Specialisation index, from the memorandum's market derivation. Each market's share of a
  // necessity divided by the share its overall size predicts, which removes market size from the
  // comparison. 1.00 sits exactly where size predicts; 1.15 marks specialisation.
  //
  // Both rows count items in one file, Internal/Resources/Research_Library/Reports/
  // AU_NZ_JP_innovation_exit_catalogue_2026-08-10.md, assembled in a single August 2026 research
  // pass under one necessity classification. The innovation row counts 79 named innovations and
  // patents and separates the markets at p = 0.012 against a random allocation of the same items.
  // The exit row counts 115 companies from that same catalogue and reads p = 0.19, so it carries
  // the same three leads without separating the markets on its own. The rows are therefore two cuts
  // of one pass, which is why the lead is taken on the innovation row alone and the exit row is
  // printed as a reading of the older market rather than as corroboration.
  //
  // Reviewed 2026-09-12, three fixes. The earlier wording called the two rows independent bases
  // that agree. The exit row also counted table ROWS, and the catalogue puts up to eight companies
  // in one row, so the unit undercounted unevenly by market; and it included three listings from
  // 1994 and 1995 that the row's own 2000-to-2026 label excludes. Fixing the window alone would
  // have moved Japan to Heal on a 1.2% margin, which is why the unit was fixed with it.
  var SPEC = {
    "AUSTRALIA":   { lead: "Heal",  inn: { Power: 0.66, Eat: 0.66, Heal: 1.66 }, exi: { Power: 0.98, Eat: 0.79, Heal: 1.12 } },
    "NEW ZEALAND": { lead: "Eat",   inn: { Power: 1.14, Eat: 1.53, Heal: 0.50 }, exi: { Power: 0.81, Eat: 1.77, Heal: 0.67 } },
    "JAPAN":       { lead: "Power", inn: { Power: 1.32, Eat: 0.74, Heal: 0.73 }, exi: { Power: 1.16, Eat: 0.90, Heal: 0.98 } }
  };
  var SPEC_BASES = [["inn", "INNOVATION / IP"], ["exi", "EXITS 2000-26"]];

  var CAPTION =
    "Each spoke is one necessity and its length is that market's specialisation index on " +
    "the innovation base. The inner ring sits at 1.00, where a market's overall size " +
    "predicts its share of a necessity, and the outer ring at 1.15, where specialisation " +
    "begins. The three measured rows beneath each panel read across markets as well as " +
    "down, because they are counts on one register and a share on one exit population.";

  var SPEC_CAPTION =
    "The specialisation index divides each market's share of a necessity by the share its overall " +
    "size predicts, which removes market size from the comparison. An index of 1.00 sits where size " +
    "predicts and 1.15 marks specialisation. On innovation and intellectual property each market " +
    "leads exactly one necessity and the three leads are different: Australia Heal at 1.66, Japan " +
    "Power at 1.32, New Zealand Eat at 1.53. That base is a catalogue of 79 named innovations and " +
    "patents, and its separation holds at p = 0.012 against a random allocation of the same items. " +
    "The exit row counts 115 companies from the same catalogue and reads p = 0.19, so it carries the " +
    "same three leads without separating the markets on its own. Exits lag innovation by a decade " +
    "or more, so the exit row reads the market of the 2000s. The fund invests against the " +
    "innovation base.";

  var MEAS_CAPTION =
    "Instruments in force and the count operative since 2020 are taken from the register on " +
    "the left of this page, on the operative date of each obligation. The listing share is the " +
    "share of winner exits realised by listing, conditional on a company reaching a winner " +
    "outcome, measured on an independent exit population.";

  // ---- geometry ----
  var VB_W = 320, VB_H = 300;   // per-panel viewBox
  var CX = 160, CY = 152;       // chart centre
  var R = 86;                   // max spoke length, at IDX_MAX
  var LBL_R = R + 20;           // axis-label radius

  /* The index scale, and the rings are its own thresholds rather than round numbers.
     1.00 is where a market's size predicts its share of a necessity and 1.15 is where
     specialisation begins, so a reader can see which spokes clear which line without a
     legend. IDX_MAX is above the largest value in SPEC (1.77 on the exit row) so no
     vertex is ever clipped by the frame. */
  var IDX_MAX = 1.80;
  var RINGS = [0.50, 1.00, 1.15, 1.50];
  var RING_LABELS = [1.00, 1.15];

  function rOf(idx) { return Math.max(0, Math.min(idx, IDX_MAX)) / IDX_MAX * R; }

  // POWER at top (-90deg), then clockwise every 120deg, matching the necessity order.
  function angle(i) { return (-90 + i * 120) * Math.PI / 180; }
  function px(i, radius) { return CX + Math.cos(angle(i)) * radius; }
  function py(i, radius) { return CY + Math.sin(angle(i)) * radius; }

  function el(name, attrs) {
    var n = document.createElementNS(SVGNS, name);
    if (attrs) for (var k in attrs) if (attrs.hasOwnProperty(k)) n.setAttribute(k, attrs[k]);
    return n;
  }


  /* The polygon the dots sample. `vals` is one index per necessity, in AXES order. */
  function idxPath(vals) {
    var d = "";
    for (var i = 0; i < AXES.length; i++) {
      var rr = rOf(vals[i]);
      d += (i === 0 ? "M" : "L") + px(i, rr).toFixed(2) + " " + py(i, rr).toFixed(2);
    }
    return d + "Z";
  }

  function anchorFor(x) {
    var d = x - CX;
    if (d > 6) return "start";
    if (d < -6) return "end";
    return "middle";
  }


  function cornerTick(pos) {
    // small mono corner tick in the accent, drawn as an L into the panel.
    var w = document.createElement("span");
    w.className = "radar-corner rc-" + pos;
    var s = el("svg", { width: "9", height: "9", viewBox: "0 0 9 9" });
    var horiz, vert;
    if (pos === "tl") { horiz = "M0 0 H9"; vert = "M0 0 V9"; }
    else if (pos === "tr") { horiz = "M9 0 H0"; vert = "M9 0 V9"; }
    else if (pos === "bl") { horiz = "M0 9 H9"; vert = "M0 9 V0"; }
    else { horiz = "M9 9 H0"; vert = "M9 9 V0"; }
    [horiz, vert].forEach(function (d) {
      s.appendChild(el("path", { d: d, stroke: "var(--hmm-accent)", "stroke-width": "1", fill: "none" }));
    });
    w.appendChild(s);
    return w;
  }

  /* Each market's lead has already produced an instrument the rest of the world adopted,
     and in every case the value settled on whoever held the record when the volume was
     built. Lifted from the memorandum's market derivation, with three figures corrected by
     the 2026-09 fact-check: the implant count is the NIDCD's December 2019 registered-device
     figure, CSIRO's licence agreements are "more than 20" on its own reachable pages, and
     the pulse-oximetry principle is dated 1972 without a month. The regulatory gates and
     the exit route for each market are stated in the prose above this chart, so nothing
     here repeats them. */
  var COUNTRY_PROSE = {
    "AUSTRALIA": "Australia's Heal lead already built an instrument the rest of the world adopted: the first multichannel cochlear implant that worked clinically and reached patients at scale, implanted in Melbourne in 1978 and cleared for adults by the FDA in 1985. Approximately 736,900 registered devices had been implanted worldwide by December 2019 on the count of the National Institute on Deafness and Other Communication Disorders, across all manufacturers. Separately the CSIRO wireless LAN patent returned around A$430M across more than 20 licence agreements.",
    "NEW ZEALAND": "New Zealand's Eat lead already built an instrument the rest of the world adopted: the practical battery energiser and the distribution system that put electric fencing on farms worldwide. The value settled on whoever held the record when the volume was built, which is the pattern this fund underwrites at the point the record is still being earned.",
    "JAPAN": "Japan's Power lead already built an instrument the rest of the world adopted: the carbonaceous anode that made a lithium-ion cell manufacturable. Pulse oximetry came from the same market, its principle conceived at Nihon Kohden in 1972. Japan also carries the clearest live case of an approval creating a category, in the first induced pluripotent stem cell medicine, approved on 6 March 2026 conditionally and for seven years."
  };

  var COUNTRY_TOKEN = { "AUSTRALIA": ["--hmm-mkt-au-dark", "#A77900"], "NEW ZEALAND": ["--hmm-mkt-nz-dark", "#C0C0C0"], "JAPAN": ["--hmm-mkt-jp-dark", "#687DB8"] };
  function countryAccent(name) { var t = COUNTRY_TOKEN[name]; return t ? __T(t[0], t[1]) : __T("--hmm-accent", "#C44539"); }

  /* Read out when a spoke label is focused. Each names what the necessity is and what the
     index on it measures, so a reader meeting the word for the first time gets the
     mechanism and not the label. */
  var AXIS_DEFS = {
    "POWER": "Power, the energy system: fuel and critical minerals, generation, storage, and the grid to end use. The index is this market's share of the innovation base in Power, divided by the share its overall size predicts.",
    "EAT": "Eat, the food and farming system: field inputs, crop and livestock, processing and distribution. The index is this market's share of the innovation base in Eat, divided by the share its overall size predicts.",
    "HEAL": "Heal, the healthcare system: prevention, diagnosis, treatment and care to end of life. The index is this market's share of the innovation base in Heal, divided by the share its overall size predicts."
  };

  function buildSVG(market, dotsOut) {
    var spec = SPEC[market.name];
    var inn = AXES.map(function (a) { return spec.inn[CAP(a)]; });
    var exi = AXES.map(function (a) { return spec.exi[CAP(a)]; });

    var svg = el("svg", { "class": "radar-svg", viewBox: "0 0 " + VB_W + " " + VB_H, role: "img" });
    svg.appendChild(el("title", {})).textContent =
      market.name + " specialisation index by necessity, innovation base and exit base";

    /* Rings first, and they carry the meaning: 1.00 is where market size predicts a share
       and 1.15 is where specialisation starts, so the two labelled rings are the reading. */
    RINGS.forEach(function (v) {
      var labelled = RING_LABELS.indexOf(v) >= 0;
      var d = "";
      for (var i = 0; i < AXES.length; i++) {
        d += (i === 0 ? "M" : "L") + px(i, rOf(v)).toFixed(2) + " " + py(i, rOf(v)).toFixed(2);
      }
      svg.appendChild(el("path", {
        "class": "radar-ring" + (labelled ? " radar-ring--key" : ""),
        d: d + "Z", fill: "none",
        stroke: "var(--hmm-text-muted,rgba(242,236,201,.6))",
        "stroke-width": labelled ? "1" : "0.5",
        "stroke-opacity": labelled ? "0.34" : "0.16",
        "stroke-dasharray": labelled ? "none" : "2 3"
      }));
      if (labelled) {
        var rl = el("text", {
          "class": "ring-lbl", x: (CX + 3).toFixed(1), y: (CY - rOf(v) + 9).toFixed(1),
          "font-size": "7", "letter-spacing": ".08em",
          fill: "var(--hmm-text-muted,rgba(242,236,201,.6))", "fill-opacity": "0.7"
        });
        rl.textContent = v.toFixed(2);
        svg.appendChild(rl);
      }
    });

    /* The exit base, drawn behind and fainter. It carries the same three leads without
       separating the markets on its own (p = 0.19), so it is a reading of the older
       market and never the basis of the lead. */
    svg.appendChild(el("path", {
      "class": "radar-exi", d: idxPath(exi), fill: "none",
      stroke: "var(--hmm-text-muted,rgba(242,236,201,.6))",
      "stroke-width": "1", "stroke-opacity": "0.38", "stroke-dasharray": "3 3",
      "stroke-linejoin": "round"
    }));

    // The innovation base. Invisible edge kept in the DOM so the flock can sample the shape.
    svg.appendChild(el("path", {
      "class": "radar-line", d: idxPath(inn), fill: "none",
      stroke: "var(--hmm-pearl,#F2ECC9)", "stroke-width": "1", "stroke-opacity": "0",
      "stroke-linejoin": "round"
    }));

    // One group per necessity: the vertex marker and its printed index. The legend chips
    // target these, so hover and focus behave as they did on the six-axis panels.
    for (var a = 0; a < AXES.length; a++) {
      var nm = CAP(AXES[a]), hue = HUES[nm], rr = rOf(inn[a]);
      var g = el("g", { "class": "series series--" + nm.toLowerCase() });
      g.setAttribute("data-series", nm);
      g.appendChild(el("circle", {
        "class": "radar-vtx", cx: px(a, rr).toFixed(2), cy: py(a, rr).toFixed(2),
        r: "3.1", fill: hue, "fill-opacity": "0.9"
      }));
      var lx = px(a, LBL_R), ly = py(a, LBL_R);
      var dy = ly < CY - 4 ? -1 : (ly > CY + 4 ? 9 : 3);
      var lab = el("text", {
        "class": "axis-lbl", "data-axis": AXES[a], tabindex: "0",
        x: lx.toFixed(1), y: (ly + dy).toFixed(1), "text-anchor": anchorFor(lx),
        "font-size": "9", "letter-spacing": ".14em",
        fill: "var(--hmm-text-muted,rgba(242,236,201,.6))"
      });
      lab.textContent = AXES[a];
      g.appendChild(lab);
      var val = el("text", {
        "class": "axis-val", x: lx.toFixed(1), y: (ly + dy + 11).toFixed(1),
        "text-anchor": anchorFor(lx), "font-size": "9", "letter-spacing": ".04em",
        fill: hue
      });
      val.textContent = inn[a].toFixed(2);
      g.appendChild(val);
      svg.appendChild(g);

      /* Dots for the flock, filling this necessity's sector of the innovation polygon so
         every dot carries its necessity's hue. Density follows the index, which is the
         constructed-form rule: the datum sets the drawing. */
      var nxt = rOf(inn[(a + 1) % AXES.length]);
      var prv = rOf(inn[(a + AXES.length - 1) % AXES.length]);
      var FILL = Math.round(34 + (inn[a] / IDX_MAX) * 96);
      for (var q = 0; q < FILL; q++) {
        var side = Math.random() < 0.5 ? -1 : 1;
        var fr = Math.random();
        var bnd = rr + ((side < 0 ? prv : nxt) - rr) * fr;
        var th = angle(a) + side * fr * (2 * Math.PI / 3) * 0.5;
        var rr2 = bnd * Math.sqrt(Math.random()) * 0.94;
        var big = Math.random() < 0.22;
        dotsOut.push({ x: CX + Math.cos(th) * rr2, y: CY + Math.sin(th) * rr2, r: big ? 1.9 : 1.2, hue: hue, s: nm });
      }
      dotsOut.push({ x: px(a, rr), y: py(a, rr), r: 2.2, hue: hue, s: nm, vtx: true });
    }

    return svg;
  }

    var svg = el("svg", { class: "radar-svg", viewBox: "0 0 " + VB_W + " " + VB_H, role: "img" });
  // (radar dots are drawn on <canvas> by the shared flock engine in render(); no SVG explode.)

  /* ---- the measured strip, read from data/market_strength.js ----
     Three rows, three different owners, generated by scripts/market-strength.mjs and
     guarded at build by scripts/check-register-figures.mjs. Nothing here is typed: MS is
     the snapshot and the listing share is parsed out of the canon sentence it carries, so
     a canon recompile that this repository has not picked up fails the deploy instead of
     printing a stale figure.

     Each bar is scaled against the largest value in its own row across the three markets,
     and that maximum is printed as the row's denominator, because a bar without a visible
     denominator is a bar a reader cannot check. */
  var MS = (typeof window !== "undefined" && window.MARKET_STRENGTH) || null;

  function listingShares() {
    if (!MS) return null;
    var out = {}, ok = true;
    ["AU", "JP", "NZ"].forEach(function (c) {
      var m = String(MS.listing_prob).match(new RegExp(c + " ([\\d.]+)%"));
      if (m) { out[c] = parseFloat(m[1]); } else { ok = false; }
    });
    return ok ? out : null;
  }

  function measRows() {
    var sh = listingShares();
    if (!MS || !MS.register || !sh) return null;
    var reg = MS.register;
    return [
      { key: "INSTRUMENTS IN FORCE", unit: "", get: function (c) { return reg[c] ? reg[c].inForce : null; }, dp: 0,
        note: "enforceable instruments this market has in force inside the mandate" },
      { key: "OPERATIVE SINCE 2020", unit: "", get: function (c) { return reg[c] ? reg[c].since2020 : null; }, dp: 0,
        note: "of those, the ones whose obligation commenced in 2020 or later" },
      { key: "LISTING SHARE", unit: "%", get: function (c) { return sh[c]; }, dp: 1,
        note: "share of winner exits realised by listing, conditional on a winner outcome" }
    ];
  }

  function buildMeas(code) {
    var rows = measRows();
    if (!rows) return null;
    var wrap = document.createElement("div");
    wrap.className = "radar-meas";
    rows.forEach(function (row) {
      var vals = ["AU", "JP", "NZ"].map(row.get).filter(function (v) { return typeof v === "number"; });
      var max = vals.length ? Math.max.apply(null, vals) : 0;
      var v = row.get(code);
      if (typeof v !== "number" || !max) return;
      var r = document.createElement("div");
      r.className = "meas-row";

      var lbl = document.createElement("span");
      lbl.className = "meas-lbl";
      lbl.textContent = row.key;
      r.appendChild(lbl);

      var track = document.createElement("span");
      track.className = "meas-track";
      var bar = document.createElement("span");
      bar.className = "meas-bar";
      bar.style.width = (v / max * 100).toFixed(1) + "%";
      track.appendChild(bar);
      r.appendChild(track);

      var num = document.createElement("span");
      num.className = "meas-val";
      num.textContent = v.toFixed(row.dp) + row.unit;
      r.appendChild(num);

      var den = document.createElement("span");
      den.className = "meas-den";
      den.textContent = "of " + max.toFixed(row.dp) + row.unit;
      r.appendChild(den);

      r.setAttribute("aria-label", row.key.toLowerCase() + ", " + v.toFixed(row.dp) + row.unit +
        ", against " + max.toFixed(row.dp) + row.unit + " for the highest of the three markets: " + row.note);
      wrap.appendChild(r);
    });
    return wrap.children.length ? wrap : null;
  }

  function buildPanel(market) {
    var panel = document.createElement("div");
    panel.className = "radar-panel";

    ["tl", "tr", "bl", "br"].forEach(function (p) { panel.appendChild(cornerTick(p)); });

    panel.setAttribute("data-market", market.name);
    panel.style.setProperty("--c", countryAccent(market.name));

    panel.addEventListener("pointerenter", function () { HOVERING++; });
    panel.addEventListener("pointerleave", function () { HOVERING = HOVERING > 0 ? HOVERING - 1 : 0; });

    var spec = SPEC[market.name];
    if (spec) panel.setAttribute("data-lead", spec.lead);

    var title = document.createElement("h3");
    title.className = "radar-title";
    title.textContent = market.name;
    panel.appendChild(title);

    var sub = document.createElement("p");
    sub.className = "radar-sub";
    sub.textContent = market.sub;
    panel.appendChild(sub);

    // body: chart on the left, prose on the right once the panel opens
    var body = document.createElement("div");
    body.className = "radar-body";
    var viz = document.createElement("div");
    viz.className = "radar-viz";
    body.appendChild(viz);
    panel.appendChild(body);

    var dotsOut = [];
    var svg = buildSVG(market, dotsOut);
    var stage = document.createElement("div");
    stage.className = "radar-stage";
    stage.appendChild(svg);
    var cv = document.createElement("canvas");
    cv.className = "radar-canvas";
    stage.appendChild(cv);
    viz.appendChild(stage);
    PANELS.push({ panel: panel, svg: svg, cv: cv, dots: dotsOut });

    // legend chips (identity never rests on colour alone)
    var legend = document.createElement("ul");
    legend.className = "radar-legend";
    SERIES.forEach(function (name) {
      var li = document.createElement("li");
      var chip = document.createElement("button");
      chip.type = "button";
      chip.className = "radar-chip u-control";
      chip.setAttribute("data-series", name);
      chip.setAttribute("aria-label", "Highlight " + name + " on " + market.name);
      var sw = document.createElement("span");
      sw.className = "swatch";
      sw.style.background = HUES[name];
      chip.appendChild(sw);
      chip.appendChild(document.createTextNode(name));
      // The lead is marked in text as well as in weight, so identity never rests on colour or
      // on a visual cue alone. The label is read out, which is why it is a span and not a glyph.
      if (spec && spec.lead === name) {
        chip.classList.add("radar-chip--lead");
        var ld = document.createElement("span");
        ld.className = "chip-lead";
        ld.textContent = "LEAD";
        chip.appendChild(ld);
        chip.setAttribute("aria-label", "Highlight " + name + " on " + market.name + ". " + name + " is this market's lead necessity.");
      }
      li.appendChild(chip);
      legend.appendChild(li);

      function raise() {
        panel.setAttribute("data-focus", name);
        SERIES.forEach(function (s2) {
          var grp = svg.querySelector('.series[data-series="' + s2 + '"]');
          if (grp) grp.classList.toggle("is-active", s2 === name);
        });
      }
      function restore() {
        panel.removeAttribute("data-focus");
        var groups = svg.querySelectorAll(".series");
        for (var i = 0; i < groups.length; i++) groups[i].classList.remove("is-active");
      }
      chip.addEventListener("mouseenter", raise);
      chip.addEventListener("mouseleave", restore);
      chip.addEventListener("focus", raise);
      chip.addEventListener("blur", restore);
    });
    viz.appendChild(legend);

    var meas = buildMeas(market.code);
    if (meas) viz.appendChild(meas);

    // The specialisation matrix for this market: the innovation row the lead is taken on, then the
    // exit row from the same catalogue, the three necessities in the same order as the legend. A
    // real table, because it is tabular and a screen reader should read the basis and the
    // necessity together.
    if (spec) {
      var tbl = document.createElement("table");
      tbl.className = "radar-spec";
      var cap = document.createElement("caption");
      cap.textContent = "Specialisation index, " + market.name.toLowerCase();
      tbl.appendChild(cap);
      var thead = document.createElement("thead");
      var hr = document.createElement("tr");
      var corner = document.createElement("td");
      hr.appendChild(corner);
      SERIES.forEach(function (n) {
        var th = document.createElement("th");
        th.scope = "col";
        th.textContent = n;
        if (spec.lead === n) th.className = "is-lead";
        hr.appendChild(th);
      });
      thead.appendChild(hr);
      tbl.appendChild(thead);
      var tb = document.createElement("tbody");
      SPEC_BASES.forEach(function (b) {
        var tr = document.createElement("tr");
        var rh = document.createElement("th");
        rh.scope = "row";
        rh.textContent = b[1];
        tr.appendChild(rh);
        SERIES.forEach(function (n) {
          var td = document.createElement("td");
          td.textContent = spec[b[0]][n].toFixed(2);
          if (spec.lead === n) td.className = "is-lead";
          tr.appendChild(td);
        });
        tb.appendChild(tr);
      });
      tbl.appendChild(tb);
      viz.appendChild(tbl);
    }

    // the prose the modal used to hold, now read in place
    var read = document.createElement("div");
    read.className = "radar-read";
    var prose = document.createElement("p");
    prose.textContent = COUNTRY_PROSE[market.name] || "";
    read.appendChild(prose);
    body.appendChild(read);

    return panel;
  }

  function render() {
    var root = document.getElementById("radars");
    if (!root) return;

    var wrap = document.createElement("div");
    wrap.className = "radar-wrap";
    MARKETS.forEach(function (m) { wrap.appendChild(buildPanel(m)); });
    root.appendChild(wrap);

    // Both captions mount here. CAPTION was written when the panels were built and was never
    // added to the document, so the scoring rule it states has been invisible since; the
    // specialisation note is new and sits beside it because a reader needs both to read a panel.
    var notes = document.createElement("div");
    notes.className = "radar-notes";
    [CAPTION, MEAS_CAPTION, SPEC_CAPTION].forEach(function (t) {
      var pnode = document.createElement("p");
      pnode.textContent = t;
      notes.appendChild(pnode);
    });
    root.appendChild(notes);

    // The re-render path. Refresh HUES in place and re-point every dot, series
    // path, swatch and panel accent; the frame loop below reads d.hue each
    // frame, so the canvas repaints on its own.
    __onTheme(function () {
      var fresh = hues();
      SERIES.forEach(function (n) { HUES[n] = fresh[n]; });
      PANELS.forEach(function (p) { p.dots.forEach(function (d) { d.hue = HUES[d.s]; }); });
      Array.prototype.forEach.call(root.querySelectorAll(".series"), function (g) {
        var n = g.getAttribute("data-series"); if (!n || !HUES[n]) return;
        Array.prototype.forEach.call(g.querySelectorAll(".radar-fill"), function (e) { e.setAttribute("fill", HUES[n]); });
        Array.prototype.forEach.call(g.querySelectorAll(".radar-line"), function (e) { e.setAttribute("stroke", HUES[n]); });
      });
      Array.prototype.forEach.call(root.querySelectorAll(".radar-chip"), function (chip) {
        var sw = chip.querySelector(".swatch"), n = chip.getAttribute("data-series");
        if (sw && n && HUES[n]) sw.style.background = HUES[n];
      });
      Array.prototype.forEach.call(root.querySelectorAll(".radar-panel"), function (p) { p.style.setProperty("--c", countryAccent(p.getAttribute("data-market"))); });
    });

    // ---- canvas flock engine: draw every panel's dots with the DWG-NEC machine physics ----
    var reduceMo = window.matchMedia && matchMedia("(prefers-reduced-motion: reduce)").matches;
    var DPR = Math.max(1, Math.min(2, window.devicePixelRatio || 1));
    function sizePanel(p) {
      var w = p.cv.clientWidth, h = p.cv.clientHeight;
      if (!w || !h) return false;
      p.cv.width = Math.round(w * DPR); p.cv.height = Math.round(h * DPR);
      p.sx = w / VB_W; p.w = w; p.h = h;
      p.ctx = p.cv.getContext("2d"); p.ctx.setTransform(DPR, 0, 0, DPR, 0, 0);
      for (var i = 0; i < p.dots.length; i++) {
        var d = p.dots[i]; d.hx = d.x * (w / VB_W); d.hy = d.y * (h / VB_H);
        if (d.cx === undefined) { d.cx = d.hx; d.cy = d.hy; d.ph = Math.random() * 6.283; }
      }
      return true;
    }
    function sizeAll() { for (var i = 0; i < PANELS.length; i++) sizePanel(PANELS[i]); }

    /* Hover must never shrink a panel. Expanding turns the body into a row and the drawing
       gives up width, so without this the panel loses height, the bottom edge retracts past
       the pointer, hover drops, and the state oscillates. Capping the stage removes most of
       the movement; this removes the rest by locking each panel to the height it settles at
       with nothing hovered, so the expansion can only ever add. Measured only when no panel
       is hovered, because a hovered panel would lock in the expanded height instead. */
    function lockHeights() {
      if (HOVERING) return;
      for (var i = 0; i < PANELS.length; i++) PANELS[i].panel.style.minHeight = "";
      var tallest = 0, h;
      for (var j = 0; j < PANELS.length; j++) {
        h = PANELS[j].panel.getBoundingClientRect().height;
        if (h > tallest) tallest = h;
      }
      if (!tallest) return;
      for (var k = 0; k < PANELS.length; k++) PANELS[k].panel.style.minHeight = Math.ceil(tallest) + "px";
    }
    /* The loop runs only while the section is on screen and the document is visible.
       It used to re-request itself every frame regardless and read getBoundingClientRect
       sixty times a second for the whole visit, drawing nothing for most of them. Every
       condition that can lift calls start(), which is a no-op while the loop is already
       running; the rect check stays so the first frame after a lift is still bounded. */
    var running = false, offscreen = false;
    function frame() {
      if (offscreen || document.hidden) { running = false; return; }
      var rr = root.getBoundingClientRect(), vh = window.innerHeight || 800;
      if (rr.bottom > -80 && rr.top < vh + 80) {
        var now = Date.now() / 1000;
        for (var pi = 0; pi < PANELS.length; pi++) {
          var p = PANELS[pi];
          if (!p.ctx && !sizePanel(p)) continue;
          var focus = p.panel.getAttribute("data-focus");
          p.ctx.clearRect(0, 0, p.w, p.h);
          for (var i = 0; i < p.dots.length; i++) {
            var d = p.dots[i];
            if (!reduceMo) { var tx = d.hx + Math.cos(now * 0.6 + d.ph) * 2.4, ty = d.hy + Math.sin(now * 0.7 + d.ph) * 2.4; d.cx += (tx - d.cx) * 0.045; d.cy += (ty - d.cy) * 0.045; }
            var a = (focus && focus !== d.s) ? 0.10 : (d.vtx ? 1 : 0.9);
            p.ctx.beginPath(); p.ctx.arc(d.cx, d.cy, d.r * p.sx, 0, 6.283); p.ctx.fillStyle = hexA(d.hue, a); p.ctx.fill();
          }
        }
      }
      requestAnimationFrame(frame);
    }
    function start() { if (running) return; running = true; requestAnimationFrame(frame); }
    sizeAll(); lockHeights();
    setTimeout(function () { sizeAll(); lockHeights(); }, 300);
    if (document.fonts && document.fonts.ready) document.fonts.ready.then(lockHeights);
    var rrt = null; addEventListener("resize", function () { clearTimeout(rrt); rrt = setTimeout(function () { sizeAll(); lockHeights(); }, 180); });
    // The panels now change width mid-animation as one expands, so the canvas has
    // to re-measure on every frame of that transition, not just on window resize.
    // Home positions move with it and the dots ease across, which is the effect.
    if (window.ResizeObserver) {
      var ro = new ResizeObserver(function (entries) {
        for (var i = 0; i < entries.length; i++) {
          for (var j = 0; j < PANELS.length; j++) if (PANELS[j].cv === entries[i].target) sizePanel(PANELS[j]);
        }
      });
      for (var pi2 = 0; pi2 < PANELS.length; pi2++) ro.observe(PANELS[pi2].cv);
    }
    if ("IntersectionObserver" in window) {
      var io = new IntersectionObserver(function (es) {
        for (var i = 0; i < es.length; i++) offscreen = !es[i].isIntersecting;
        start();
      }, { rootMargin: "80px 0px", threshold: 0 });
      io.observe(root);
    }
    document.addEventListener("visibilitychange", start);
    start();

    // axis-definition popups (hover or keyboard-focus an axis label)
    var tip = document.createElement("div");
    tip.className = "radar-tip"; tip.setAttribute("role", "tooltip"); tip.setAttribute("aria-hidden", "true");
    root.appendChild(tip);
    function showTip(node) {
      var name = node.getAttribute("data-axis"), def = AXIS_DEFS[name];
      if (!def) return;
      tip.textContent = def; tip.classList.add("on"); tip.setAttribute("aria-hidden", "false");
      var r = node.getBoundingClientRect(), tr = tip.getBoundingClientRect();
      var x = r.left + r.width / 2 - tr.width / 2;
      x = Math.max(10, Math.min(window.innerWidth - tr.width - 10, x));
      var y = r.top - tr.height - 8; if (y < 10) y = r.bottom + 8;
      tip.style.left = x + "px"; tip.style.top = y + "px";
    }
    function hideTip() { tip.classList.remove("on"); tip.setAttribute("aria-hidden", "true"); }
    function axisFrom(e) { var t = e.target; return (t && t.closest) ? t.closest(".axis-lbl") : null; }
    root.addEventListener("mouseover", function (e) { var a = axisFrom(e); if (a) showTip(a); });
    root.addEventListener("mouseout", function (e) { if (axisFrom(e)) hideTip(); });
    root.addEventListener("focusin", function (e) { var a = axisFrom(e); if (a) showTip(a); });
    root.addEventListener("focusout", function (e) { if (axisFrom(e)) hideTip(); });
  }

  if (document.readyState === "complete" || document.readyState === "interactive") {
    render();
  } else {
    window.addEventListener("load", render);
  }
})();
