/* Counts the innovation and exit catalogue into data/catalogue_counts.js, so the sourcing
   section can state how many companies the map holds per market without a figure being typed.

   WHY THIS EXISTS. Until 2026-09-15 the sourcing section carried a scrolling stream of every
   named company in catalogue.js. The general partner ruled the names off the served page, and
   the section now states the counts instead. A count typed into index.html is a figure with no
   owner, which the site rule forbids, so the counts are written here from the data file and
   the page reads them at render. scripts/check-register-figures.mjs recomputes them from
   catalogue.js on every build and fails the deploy when the snapshot is behind.

   WHAT IS COUNTED. catalogue.js holds one row per catalogue entry, in five categories per
   market: exits (M&A, IPO, USD 500M and above, some private), hardware innovations, software
   innovations, and IP and patents. An exit row can name several companies at once (a listed
   cohort written as one row), so COMPANIES splits an exit row's name on the comma and counts
   the names; INNOVATIONS counts the hardware, software and IP rows, one item per row, which is
   how the research catalogue itself counts them. catalogue.js is no longer loaded by any page;
   it stays in the repository as the owner this script reads.

   Usage:  node scripts/catalogue-counts.mjs            print the counts and compare the snapshot
           node scripts/catalogue-counts.mjs --write    rewrite data/catalogue_counts.js */
import fs from 'node:fs';

export const SNAPSHOT = 'data/catalogue_counts.js';
export const MARKETS = ['AU', 'JP', 'NZ'];
const INNOVATION = new Set(['Hardware', 'Software', 'IP']);

export function readCatalogue(file = 'catalogue.js') {
  const ctx = {};
  new Function('window', fs.readFileSync(file, 'utf8') + '\nwindow.__ = CATALOGUE;')(ctx);
  if (!Array.isArray(ctx.__)) throw new Error(`${file} did not define CATALOGUE`);
  return ctx.__;
}

export function count(rows) {
  const out = { total: { companies: 0, innovations: 0 } };
  for (const c of MARKETS) out[c] = { companies: 0, innovations: 0 };
  for (const r of rows) {
    if (!out[r.m]) throw new Error(`catalogue row for an unknown market: ${r.m}`);
    if (r.cat === 'Exit') {
      const n = String(r.name).split(',').map(s => s.trim()).filter(Boolean).length;
      out[r.m].companies += n; out.total.companies += n;
    } else if (INNOVATION.has(r.cat)) {
      out[r.m].innovations += 1; out.total.innovations += 1;
    } else {
      throw new Error(`catalogue row with an unknown category: ${r.cat}`);
    }
  }
  return out;
}

export function readSnapshot(file = SNAPSHOT) {
  const ctx = {};
  new Function('window', fs.readFileSync(file, 'utf8') + '\nwindow.__ = CATALOGUE_COUNTS;')(ctx);
  if (!ctx.__) throw new Error(`${file} did not define CATALOGUE_COUNTS`);
  return ctx.__;
}

export function same(a, b) {
  for (const c of [...MARKETS, 'total']) {
    for (const k of ['companies', 'innovations']) if (!a[c] || !b[c] || a[c][k] !== b[c][k]) return false;
  }
  return true;
}

const isMain = process.argv[1] && process.argv[1].endsWith('catalogue-counts.mjs');
if (isMain) {
  const counts = count(readCatalogue());
  console.log('market   companies   innovations');
  for (const c of [...MARKETS, 'total']) console.log(`${c.padEnd(8)} ${String(counts[c].companies).padStart(9)}   ${String(counts[c].innovations).padStart(11)}`);
  if (process.argv.includes('--write')) {
    const body = {
      _note: 'Written by scripts/catalogue-counts.mjs --write from catalogue.js. Never hand-edit. Companies counts the names on exit rows; innovations counts the hardware, software and IP rows.',
      _public: 'This file sits in the published root and is fetchable by anyone. It carries counts of catalogued companies and innovations per market, which are measured facts about a market. No company name and no fund position goes in here: the public wall of 2026-07-25 applies to this file exactly as it applies to a page.',
      compiled: new Date().toISOString().slice(0, 10),
      counts,
    };
    const text = '/* GENERATED by scripts/catalogue-counts.mjs --write. Do not hand-edit.\n' +
      '   Regenerate after a change to catalogue.js:\n' +
      '     node scripts/catalogue-counts.mjs --write\n' +
      '   scripts/check-register-figures.mjs fails the deploy when this file and catalogue.js disagree. */\n' +
      'var CATALOGUE_COUNTS = ' + JSON.stringify(body, null, 2) + ';\n' +
      "if (typeof window !== 'undefined') window.CATALOGUE_COUNTS = CATALOGUE_COUNTS;\n";
    fs.writeFileSync(SNAPSHOT, text);
    console.log(`\nwrote ${SNAPSHOT}`);
  } else if (fs.existsSync(SNAPSHOT)) {
    const snap = readSnapshot();
    console.log(same(snap.counts, counts) ? `\nok    ${SNAPSHOT} matches catalogue.js` : `\nFAIL  ${SNAPSHOT} is behind catalogue.js. Run: node scripts/catalogue-counts.mjs --write`);
    if (!same(snap.counts, counts)) process.exit(1);
  }
}
